/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

public class App {
    public String getGreeting() {
        return "Hello world, welcome to bitmap.";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());

        Bitmap test = new Bitmap("src/assets/mario.bmp", "src/assets/", "test.bmp");
        Bitmap testBlue = new Bitmap("src/assets/mario.bmp", "src/assets/", "blue-mario.bmp");

        test.bitTransformBlackWhite();
        testBlue.bitTransformBluify();
    }

}
